spring:
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    gateway:
      routes:
      - id: sp-api
        uri: lb://sp-api
        predicates:
          - Path=/sp-api/**
        filters:
          - StripPrefix=1
          - CircuitBreaker=spApiCircuitBreaker
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 5
              redis-rate-limiter.burstCapacity: 5
      - id: sp-auth
        uri: lb://sp-auth
        predicates:
          - Path=/sp-auth/**
        filters:
          - StripPrefix=1