spring:
  cloud:
    gateway:
      routes:
      - id: sp-api
        uri: lb://sp-api
        predicates:
          - Path=/sp-api/**
        filters:
          - StripPrefix=1
          - CircuitBreaker=spApiCircuitBreaker
      - id: sp-auth
        uri: lb://sp-auth
        predicates:
          - Path=/sp-auth/**
        filters:
          - StripPrefix=1